
include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = libUIKit
ADDITIONAL_OBJCFLAGS += -fblocks
libUIKit_INCLUDE_DIRS += -I/usr/include/i386-linux-gnu
libUIKit_HEADER_FILES = \
        UIView.h \
	UIImage.h \
	UIWindow.h \
	NSView+UIKit.h \
	UIKitView.h \
	UIApplicationDelegate.h \
	NSApplication+UIKit.h \
	UIKit.h \
	UIScreen.h \
	UIGeometry.h \
	UIGraphics.h \
	UIEvent.h \
	UIResponder.h \
	UIColor.h \
	UITouch.h \
	UIApplication.h \
	UIInterface.h \
	UIImageView.h \
	UIScrollView.h \
	UITableView.h \
	UITableViewCell.h \
	UIFont.h \
	UILabel.h \
	UIStringDrawing.h \
	UIDevice.h \
	UIAccessibility.h \
	UIAccessibilityElement.h \
	UIControl.h \
	UIButton.h \
	UIBezierPath.h \
	UIViewController.h \
	UIScreenMode.h \
	UIActionSheet.h \
	UIAlertView.h \
	UIControl.h \
	UIButton.h \
	UIBezierPath.h \
	UIViewController.h \
	UIScreenMode.h \
	UIActionSheet.h \
	UIAlertView.h \
	UITextField.h \
	UINavigationItem.h \
	UINavigationController.h \
	UIBarItem.h \
	UIBarButtonItem.h \
	UIPasteboard.h \
	UITextInputTraits.h \
	UIWebView.h \
	UIToolbar.h \
	UITabBar.h \
	UITabBarItem.h \
	UISegmentedControl.h \
	UIActivityIndicatorView.h \
	UIPopoverController.h \
	UINavigationBar.h \
	UITextView.h \
	UIDataDetectors.h \
	UITableViewController.h \
	UISearchBar.h \
	UISearchDisplayController.h \
	UIImagePickerController.h \
	UINibLoading.h \
	UIGestureRecognizer.h \
	UITapGestureRecognizer.h \
	UILongPressGestureRecognizer.h \
	UISplitViewController.h \
	UITabBarController.h \
	UISwitch.h \
	UISlider.h \
	UIAcceleration.h \
	UIAccelerometer.h \
	UIMenuController.h \
	UIMenuItem.h \
	UIViewAdapter.h \
	UIPageControl.h \
	UIProgressView.h \
	UIPickerView.h \
	UIPanGestureRecognizer.h \
	UIPinchGestureRecognizer.h \
	UIRotationGestureRecognizer.h \
	UISwipeGestureRecognizer.h \
	UIDatePicker.h \
	UIKey.h \
	UIScrollWheelGestureRecognizer.h \
	UINSCellControl.h \
	CALayer+UIKitCompatibility.h \
	NSFetchedResultsController.h \

libUIKit_HEADER_FILES_INSTALL_DIR = UIKit
libUIKit_OBJC_FILES = \
	UIView.m \
	UIImage.m \
	UIWindow.m \
	NSView+UIKit.m \
	UIKitView.m \

include $(GNUSTEP_MAKEFILES)/library.make
